
name: 'gxpdf' #only lowercase and underscores
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths:    ["models"]      # definitions
analysis-paths: ["analysis"]    # https://docs.getdbt.com/docs/build/analyses
test-paths:     ["tests"]       # validation logic
seed-paths:     ["data"]      # logic for loading .csv files directly. currently not used. https://docs.getdbt.com/docs/build/seeds
macro-paths:    ["macros"]      
snapshot-paths: ["snapshots"]   # https://docs.getdbt.com/docs/build/snapshots

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Configuring models
models:
  gxpdf:
    20_bronze_polished:
      +materialized: view
      +docs:
        node_color: "silver"
      #schema per source system defined in models
    30_silver:
      +materialized: view
      +docs:
        node_color: "silver"
      # +schema: Public from environment setting
    40_gold:
      +materialized: view
      +docs:
        node_color: "gold"
      # +schema: Public from environment setting
      sales:
        +schema: sales

# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.