
version: 2

models:
    - name: makt
      description: "material descriptions"
      columns:
          - name: matnr
            description: "material number"
            tests:
                - not_null
