
version: 0

sources:
  - name: SAP_S4H_LSD200
    tables:
      - name: makt
      - name: mara
      - name: vbak
      - name: vbab
      - name: vbbe
      - name: vbep
      - name: vbfa

  - name: stripe
    tables:
      - name: payments
