
version: 1

sources:
  - name: SAP_S4H_LSD200    #'schema name' defaults to source
    tables:
      - name: makt
      - name: mara
      - name: vbak
      - name: vbab
      - name: vbbe
      - name: vbep
      - name: vbfa