# This is a basic workflow to help you get started with Actions

name: CI_Tranformations_SQL_Linter_Piperider

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "10-production" branch
  pull_request:
    branches: [ "10-production" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
run:
...
SQLFLUFF:
  runs-on: ubuntu-latest
  - name: Install SQLFluff
  run: pip install sqlfluff sqlfluff-templater-dbt
  - name: Run SQLFluff
  run: sqlfluff lint <dir with sql files: e.g. models OR models/marts>/
 
 piperider-compare:
    runs-on: ubuntu-latest
    permissions:
    pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - name: PipeRider Compare

    uses: InfuseAI/piperider-compare-action@v1
    with:
      cloud_api_token: ${{ secrets.PIPERIDER_CLOUD_TOKEN_ID }}
      cloud_project: ${{ secrets.PIPERIDER_API_PROJECT }}
      upload: true
      share: true
