name: DBT artifacts
on:
  pull_request:
    branches: [ "10-production" ]

jobs:
  refresh_manifest:
    runs-on: ubuntu-latest
    steps:
    - name: trigger manifest refresh
      if: github.base_ref == '10-production'
      run: |
        RESPONSE=$(curl -v -H "Authorization:Token ${{ secrets.DBTCLOUDAPIKEY }}" -H "Content-Type:application/json" -d '{"cause":"Triggered by Github Actions. PR to production","git_branch":"10-production"}' https://cloud.getdbt.com/api/v2/accounts/228234/jobs/513698/run/)
        STATUSCODE=$(echo "$RESPONSE" | jq '.status.code')
        echo "$RESPONSE" | jq '.status.user_message'
        if [[ $STATUSCODE != 200 ]]; then echo "$RESPONSE" && bash -c "exit 1"; fi
